{% set name = "sphinx-autoapi" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 04643fc50485039294ace8b660d0d1b821a1686824a975725a5106e8cf1fb30b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2,<4
  run:
    - python >={{ python_min }}
    - astroid >=3.0
    - jinja2
    - pyyaml
    - sphinx >=7.4.0
    - stdlib-list

test:
  requires:
    - python {{ python_min }}
  imports:
    - autoapi

about:
  home: http://github.com/rtfd/sphinx-autoapi
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.mit
  summary: Sphinx auto API documentation generator
  doc_url: http://sphinx-autoapi.readthedocs.io/en/latest/
  dev_url: https://github.com/rtfd/sphinx-autoapi

extra:
  recipe-maintainers:
    - timkpaine
    - honnorat
    - CurtLH
    - ChrisBarker-NOAA
    - bjlittle
